language: java

jdk:
  - openjdk8

install: mvn install -DskipTests -Dgpg.skip
script:
    mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install -Dgpg.skip=true -Dmaven.test.failure.ignore=false sonar:sonar -Dsonar.login=$SONAR_LOGIN -Dsonar.host.url=$SONAR_HOST

