language: java

jdk:
  - openjdk10

install: echo "Skipping install stage, dependencies will be downloaded during test stages."
test: echo "Skipping test stage, using scripts to perform unit tests and quality metrics."

script:
    mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install -DskipITs -Dgpg.skip=true -Dmaven.test.failure.ignore=false sonar:sonar -Dsonar.login=$SONAR_LOGIN -Dsonar.host.url=$SONAR_HOST

